### ISSUE TITLE
Add a `bundle` tox environment

### ISSUE THREAD

**Issue by azmeuk** [python-scim/scim2-cli#15]
A tox env dedicated to bundle would be nice to check this does not break during development.

This could be a base:

```toml
[tool.tox.env.bundle]
dependency_groups = ["bundle"]
whitelist_externals = ["ldd", "ldconfig"]
commands = [
    ["pyinstaller", "--clean", "--name", "scim2", "--log-level", "WARN", "--onefile", "scim2_cli/__init__.py"],
    ["python", "dist/scim2", "--help"],
]
```

This should be fixed, because it generates the following error message:

```console
tox -e bundle -r
bundle: remove tox env folder /home/eloi/dev/python-scim/scim2-cli/.tox/bundle
bundle: venv> .venv/bin/uv venv -p /home/eloi/dev/python-scim/scim2-cli/.venv/bin/python3 --allow-existing /home/eloi/dev/python-scim/scim2-cli/.tox/bundle
bundle: uv-sync> uv sync --frozen --no-dev --group bundle
bundle: commands[0]> pyinstaller --clean --name scim2 --log-level WARN --onefile scim2_cli/__init__.py
26372 WARNING: Unrecognised line of output 'Cache généré par : ldconfig (GNU libc) stable release version 2.40' from ldconfig
26768 WARNING: ldd warnings for '/usr/lib/libgcc_s.so.1':
ldd: attention : vous n'avez pas la permission d'exécution pour `/usr/lib/libgcc_s.so.1'
bundle: commands[1]> python dist/scim2 --help
  File "/home/eloi/dev/python-scim/scim2-cli/dist/scim2", line 1
    ELF
SyntaxError: source code cannot contain null bytes
bundle: exit 1 (0.02 seconds) /home/eloi/dev/python-scim/scim2-cli> python dist/scim2 --help pid=98609
  bundle: FAIL code 1 (32.38=setup[0.36]+cmd[31.99,0.02] seconds)
  evaluation failed :( (32.45 seconds)
```
